repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
    - id: trailing-whitespace
      args: [--markdown-linebreak-ext=md]
    - id: check-merge-conflict
    - id: check-yaml
      args: [--unsafe]
    - id: no-commit-to-branch
    - id: end-of-file-fixer
-   repo: https://github.com/pre-commit/pygrep-hooks
    rev: v1.10.0
    hooks:
    - id: python-use-type-annotations
    - id: text-unicode-replacement-char
- repo: https://github.com/myint/docformatter
  rev: v1.7.5
  hooks:
    - id: docformatter
      additional_dependencies:
      - tomli
      args:
      - --in-place
-   repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.4.8
    hooks:
        - id: ruff
          args: [ --fix ]
        - id: ruff-format
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.10.0
    hooks:
    -   id: mypy
        args:
        - --strict
        - --implicit-reexport
        - --show-error-codes
        - --show-error-context
        - --show-column-numbers
        additional_dependencies:
            - pytest-mypy
            - jwskate>=0.11.1
            - types-requests
            - requests_mock
            - flask
            - freezegun
            - furl
