repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
    - id: trailing-whitespace
      args: [--markdown-linebreak-ext=md]
    - id: check-merge-conflict
    - id: check-yaml
      args: [--unsafe]
    - id: no-commit-to-branch
-   repo: https://github.com/pre-commit/pygrep-hooks
    rev: v1.10.0
    hooks:
    - id: python-use-type-annotations
    - id: text-unicode-replacement-char
- repo: https://github.com/myint/docformatter
  rev: v1.7.5
  hooks:
    - id: docformatter
      additional_dependencies:
      - tomli
      args:
      - --in-place
-   repo: https://github.com/asottile/blacken-docs
    rev: 1.16.0
    hooks:
        - id: blacken-docs
-   repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.1.9
    hooks:
        - id: ruff
          args: [ --fix ]
        - id: ruff-format
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.8.0
    hooks:
    -   id: mypy
        args:
        - --strict
        - --implicit-reexport
        - --show-error-codes
        - --show-error-context
        - --show-column-numbers
        additional_dependencies:
            - pytest-mypy
            - jwskate>=0.9.0
            - types-requests
            - requests_mock
            - flask
            - freezegun
            - furl
