site_name: requests_oauth2client
# site_url: http://www.jieyu.ai
repo_url: https://github.com/guillp/requests_oauth2client
repo_name: requests_oauth2client
strict: true
watch:
  - requests_oauth2client
  - README.md
nav:
  - Home: index.md
  - Installation: installation.md
  - API: api.md
  - Contributing: contributing.md
  - Authors: authors.md
  - Changelog: history.md
theme:
  name: material
  language: en
  #logo: assets/logo.png
  palette:
    primary: light blue
  features:
    - navigation.indexes
    - navigation.tabs
    - navigation.instant
    - navigation.tabs.sticky
    - navigation.footer
    - content.code.copy
    - content.action.view
markdown_extensions:
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.tabbed
  - attr_list
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.highlight:
      linenums: true
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - pymdownx.details
  - admonition
  - toc:
      baselevel: 2
      permalink: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify {kwds: {case: lower}}
  - meta
plugins:
  - include-markdown
  - search:
      lang: en
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          options:
              filters:
                  - "!^_"
                  - "^__init__"
                  - "!^utils"
              members_order: source
              show_root_heading: true
              show_submodules: true
          import:
            - https://requests.readthedocs.io/en/master/objects.inv

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/guillp/requests_oauth2client
      name: Github
    - icon: material/email
      link: "mailto:guill.p.linux@gmail.com"
