site_name: requests_oauth2client
# site_url: http://www.jieyu.ai
repo_url: https://github.com/guillp/requests_oauth2client
repo_name: requests_oauth2client
strict: false
nav:
  - Home: index.md
  - Installation: installation.md
  - Usage: usage.md
  - API: api.md
  - Contributing: contributing.md
  - Authors: authors.md
  - Changelog: history.md
theme:
  name: material
  language: en
  #logo: assets/logo.png
  palette:
    primary: light blue
  features:
    - navigation.indexes
    - navigation.tabs
    - navigation.instant
    - navigation.tabs.sticky
markdown_extensions:
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.tabbed
  - attr_list
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.highlight:
      linenums: true
  - pymdownx.superfences
  - pymdownx.details
  - admonition
  - toc:
      baselevel: 2
      permalink: true
      slugify: !!python/name:pymdownx.slugs.uslugify
  - meta
plugins:
  - include-markdown
  - search:
      lang: en
  - mkdocstrings:
      watch:
        - requests_oauth2client
        - README.md
      handlers:
          python:
              import:
                  - https://docs.python-requests.org/en/master/objects.inv

extra:
  social:
    - icon: fontawesome/brands/twitter
      # replace with your own tweet link below
      link: http://www.jieyu.ai
      name: Tweet
    - icon: fontawesome/brands/facebook
      # replace with your own facebook link below
      link: http://www.jieyu.ai
      name: Facebook
    - icon: fontawesome/brands/github
      link: https://github.com/guillp/requests_oauth2client
      name: Github
    - icon: material/email
      link: "mailto:guill.p.linux@gmail.com"
  # to enable disqus, uncomment the following and put your disqus id below
  # disqus: disqus_id
# uncomment the following and put your google tracking id below to enable GA
#google_analytics:
  #- UA-xxx
  #- auto
