[tool]
[tool.poetry]
name = "requests_oauth2client"
version = "1.0.0-alpha.0"
homepage = "https://github.com/guillp/requests_oauth2client"
description = "An OAuth2.x Client based on requests."
authors = ["Guillaume Pujol <guill.p.linux@gmail.com>"]
readme = "README.md"
license =  "Apache-2.0"
classifiers=[
    'Development Status :: 2 - Pre-Alpha',
    'Intended Audience :: Developers',
    'License :: OSI Approved :: Apache Software License',
    'Natural Language :: English',
    'Programming Language :: Python :: 3',
    'Programming Language :: Python :: 3.7',
    'Programming Language :: Python :: 3.8',
    'Programming Language :: Python :: 3.9',
    'Programming Language :: Python :: 3.10',
]
packages = [
    { include = "requests_oauth2client" },
    { include = "tests", format = "sdist" },
]

[tool.poetry.dependencies]
python = ">=3.7,<4.0"

requests = "^2.19.0"
cryptography = "^3.0.0"
furl = "^2.1.2"

[tool.poetry.dev-dependencies]
black  = "^22.1.0"
coverage = "^6.3"
isort  = "^5.9.3"
flake8  = "^4.0.1"
flake8-docstrings = "^1.6.0"
flake8-rst-docstrings = "^0.2.3"
flask = "^2.0.1"
livereload = "^2.6.3"
mypy = "^0.931"
mkdocs  = "^1.2.3"
mkdocstrings = "^0.17.0"
mkdocs-autorefs = "^0.3.0"
mkdocs-include-markdown-plugin  = "^3.2.3"
mkdocs-material  = "^8.1.9"
mkdocs-material-extensions  = "^1.0.1"
pip  = "^22.0"
pre-commit = "^2.12.0"
pytest  = "^6.2.5"
pytest-cov  = "^3.0.0"
requests-mock = "^1.9.3"
toml = "^0.10.2"
tox  = "^3.20.1"
twine  = "^3.3.0"
types-requests = "^2.25.6"
types-cryptography = "^3.3.5"
virtualenv  = "^20.2.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.black]
line-length = 88
include = '\.pyi?$'
exclude = '''
/(
    \.eggs
  | \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | _build
  | buck-out
  | build
  | dist
)/
'''

[tool.mypy]
strict = true
implicit_reexport = true
show_error_context = true
show_column_numbers = true
show_error_codes = true
pretty = true
warn_unused_configs = true
warn_unused_ignores = true
warn_redundant_casts = true
